name: module3_task0

on:
  push:
    branches: [master]
  schedule:
    - cron: "30 00 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Run make help"
        run: cd module3_task0 && make help
