---
name: module3_task2

on:
  push:
    branches: [master] 
  schedule:
    - cron: "30 00 * * *"

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup"
        run: cd module3_task2 && ./setup.sh

      - name: "make build" #execute makebuild command
        run: cd module3_task2 && make build

      # Check syntax on markdown files
      - name: Run markdownlint on markdown files
        run: make lint -C module3_task2/

      # Produce a zip file containing the dist folder
      - name: Archive the dist folder inside a zip file
        run: |
          cd module3_task2 && make package

      # Go to the right folder and execute 'make build'
      - name: Build the application
        run: make build -C module3_task2/

      # Additional steps form past module
      - name: Run additional make rules
        run: |
          make unit-tests -C module3_task2/
          make integration-tests -C module3_task2/
          make validate -C module3_task2/

      # Archive the zip file as artifact
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: Archive awesome-website.zip as artifact
          path: module3_task2/awesome-website.zip
